version: 0.0
os: linux
files:
  - source: /
    destination: /opt/apache-tomcat-8.5.23/webapps
  
 hooks:
  BeforeInstall:
    - location: /opt/apache-tomcat-8.5.23/bin/startup.sh
      timeout: 300
      runas: root
